config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/profile/:handle' => 'users#show', as: 'user'
  get 'users/profile/:handle/style' => 'users#edit', as: 'user_edit'
  put 'users/profile/:handle' => 'users#update'
  post 'users/profile/:handle' => 'users#sync_data', as: 'user_sync_data'
  get ':handle' => 'blog_items#index', as: 'user_index'

  resources :users, only: [] do
  	resources :post_items
  	resources :flickr_items
  	resources :medium_items
  	resources :flickr_details, except: [:index, :show]
  	resources :medium_details, except: [:index, :show]
  end

  resources :post_items, :medium_items, :flickr_items, only: [] do
  	resources :comments, only: [:create]
  end
end

app/models/flickr_item.rb
class FlickrItem < ActiveRecord::Base
	has_one :blog_item, as: :item, dependent: :destroy

	def author
		blog_item.author
	end

	def flickr_url(nsid, photo_id)
		"https://www.flickr.com/photos/#{nsid}/#{photo_id}"
	end

	def direct_url(farm, server, photo_id, secret)
		"https://farm#{farm}.staticflickr.com/#{server}/#{photo_id}_#{secret}_z.jpg"
	end

	def owner_nsid
		FlickrDetail.find_by_user_id(self.blog_item.user_id).nsid
	end

	def self.process_from_api(user, items)
		items.each do |item|
			if user.flickr_items.where(photo_id: item[:photo_id]).blank?
				flickr_item = FlickrItem.create!(
					title: item[:title],
					photo_id: item[:photo_id],
					description: item[:description],
					posted_at: item[:posted_at],
					farm: item[:farm],
					server: item[:server],
					secret: item[:secret]
					)
				flickr_item.update_attribute(:title, "(no title)") if flickr_item.title.blank? 
				flickr_item.blog_item = BlogItem.create!(user_id: user.id, item_type: 'FlickrItem')
			end
		end
	end
end

app/controllers/flickr_items_controller.rb
class FlickrItemsController < ApplicationController
	before_action :find_photo, only: [:edit, :update, :show]
	# doesn't work because instead of id ther's the user handle in the url
	before_action :authenticate_user!, except: [:show, :index]

	def index
		@photos = current_user.flickr_items.order(created_at: :desc) # when link in index blog items won't work
	end

	def edit
	end

	def update
		@photo.update(title: params[:title], description: params[:description])
		tags = clean_tags_array(params[:tags])
		@photo.blog_item.create_or_find_tags(tags)
		redirect_to user_flickr_item_path(current_user.handle, @photo), notice: "Photo updated successfully."
	end

	def show
		@blog_user = @blog_user = User.find_by_handle(params[:user_id])
	end

	def destroy
		photo = FlickrItem.find(params[:id])
		FlickrItem.destroy(photo)
		redirect_to user_flickr_items_path(params[:user_id]), notice: "Photo deleted successfully." #photo.blog_item = nil, ?
	end

	private

	def find_photo
		@photo = FlickrItem.find(params[:id])
	end

	# def photo_item_params
	# 	params.require(:flickr_item).permit(:title, :description)
	# end

	def clean_tags_array(tags)
		tags.delete(' ').split(',')
	end
end

app/views/flickr_items/_flickr_item.html.erb
<h2><%= link_to flickr_item.title, user_flickr_item_path(params[:handle], flickr_item) %></h2>

<p class="meta">taken <%= time_ago_in_words(flickr_item.posted_at) %> ago</p>

<a data-flickr-embed="true" href="<%= flickr_item.flickr_url(flickr_item.owner_nsid, flickr_item.photo_id) %>">
	<img src="<%= flickr_item.direct_url(flickr_item.farm, flickr_item.server, flickr_item.photo_id, flickr_item.secret) %>" alt=<%= flickr_item.title %>>
</a>
<script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

<p><%= simple_format(flickr_item.description) %></p>

<p>	
	<% flickr_item.blog_item.tags.each do |tag| %>
		<span class="label"><%= link_to tag.name, "/#{flickr_item.author.handle}?tag=#{tag.name}" %></span>
	<% end %>
</p>

<% if current_user && current_user.id == flickr_item.blog_item.user_id %>
<p><%= link_to 'Edit', edit_user_flickr_item_path(current_user, flickr_item), class: "action-link" %></p>
<% end %>

app/views/flickr_items/edit.html.erb
<h2>Update photo</h2>

<%= form_tag user_flickr_item_path, method: :put do %>
  <%= label_tag :title %>
  <%= text_field_tag :title, @photo.title %>
  <%= label_tag :description %>
  <%= text_area_tag :description, @photo.description %>
  <%= label_tag :tags, "Tags (separated by comma)" %>
  <%= text_field_tag :tags, @tags %>
  <%= submit_tag "Update photo", class: "button button-primary" %>
<% end %>

<%= link_to 'Delete', user_flickr_item_path, method: :delete, data: { confirm: "Are you sure?" }, class: "action-link" %>

app/views/flickr_items/index.html.erb
<h2>Photos from Flickr</h2>
<% unless @photos.blank? %>
	<table>
	<% @photos.each do |photo| %>
		<tr>
			<th><%= link_to photo.title.blank? ? "(No title)" : photo.title , user_flickr_item_path(params[:user_id], photo), class: "content-link" %></th>
			<td><%= link_to 'Edit', edit_user_flickr_item_path(current_user, photo), class: "action-link" %></td>
			<td><%= link_to 'Delete', user_flickr_item_path(current_user, photo), method: :delete, data: { confirm: "Are you sure?" }, class: "action-link" %></td>
		</tr>
	<% end %>
		
	</table>
<% else %>
	<p>No photos yet!</p>
<% end %>
	

app/views/flickr_items/show.html.erb
<h1><%= link_to @blog_user.handle, user_index_path(@blog_user.handle) %></h1>
<h2><%= @photo.title %></h2>

<p class="meta">taken <%= time_ago_in_words(@photo.posted_at) %> ago</p>

<a data-flickr-embed="true" href="<%= @photo.flickr_url(@photo.owner_nsid, @photo.photo_id) %>">
	<img src="<%= @photo.direct_url(@photo.farm, @photo.server, @photo.photo_id, @photo.secret) %>" alt=<%= @photo.title %>>
</a>
<script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

<p><%= simple_format(@photo.description) %></p>

<p>	
	<% @photo.blog_item.tags.each do |tag| %>
		<span class="label"><%= link_to tag.name, "/#{@photo.author.handle}?tag=#{tag.name}" %></span>
	<% end %>
</p>

<%= render partial: 'shared/tweet', :locals => {item: @photo} %>

<% if current_user && current_user.id == @photo.blog_item.user_id %>
<p><%= link_to 'Edit', edit_user_flickr_item_path(current_user, @photo), class: "action-link" %></p>
<% end %>

<h3 class="comments">Comments</h3>

<%= render partial: 'shared/comment_form', :locals => {item: @photo} %>
<%= render partial: 'shared/comment', collection: @photo.blog_item.comments %>

<%= link_to "Back", :back %>