config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/profile/:handle' => 'users#show', as: 'user'
  get 'users/profile/:handle/style' => 'users#edit', as: 'user_edit'
  put 'users/profile/:handle' => 'users#update'
  post 'users/profile/:handle' => 'users#sync_data', as: 'user_sync_data'
  get ':handle' => 'blog_items#index', as: 'user_index'

  resources :users, only: [] do
  	resources :post_items
  	resources :flickr_items
  	resources :medium_items
  	resources :flickr_details, except: [:index, :show]
  	resources :medium_details, except: [:index, :show]
  end

  resources :post_items, :medium_items, :flickr_items, only: [] do
  	resources :comments, only: [:create]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_items, dependent: :destroy
  has_one :flickr_detail, dependent: :destroy
  has_one :medium_detail, dependent: :destroy
  has_many :post_items, through: :blog_items, source: :item, source_type: "PostItem"
  has_many :flickr_items, through: :blog_items, source: :item, source_type: "FlickrItem"
  has_many :medium_items, through: :blog_items, source: :item, source_type: "MediumItem"
 
  validates :handle, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show
		@user = current_user
	end

	def edit
	end

	def update
		# updates styles
		current_user.update(user_params)
		redirect_to user_index_path(current_user.handle), notice: "Style updated successfully."
	end

	def sync_data
  	user = User.find_by_handle(params[:handle])
		if user.medium_detail
			MediumContentService.items(user)
		end
		if user.flickr_detail
			FlickrContentService.items(user)
		end
		redirect_to user_index_path(user.handle), notice: "Content added successfully!"
	end

	private

	def user_params
		params.require(:user).permit(:styles)
	end
end

app/views/users/_edit.html.erb
<%= form_for current_user, method: "put" do |f| %>
	<%= f.radio_button("styles", "default") %>
	<label for="user_styles_default">Ruby (default)</label><br />
	<%= f.radio_button("styles", "notebook") %>
	<label for="user_styles_notebook">Notebook</label><br />
	<%= f.radio_button("styles", "pulp") %>
	<label for="user_styles_pulp">Pulp</label><br />
	<%= f.submit "Update style", class: 'button' %>
<% end %>

app/views/users/edit.html.erb
<h2>Choose blog style</h2>

<%= render partial: 'edit' %>
<!--
	<%= form_for current_user, method: "put" do |f| %>
		<%= f.radio_button("styles", "default") %>
		<label for="user_styles_default">Ruby (default)</label><br />
		<%= f.radio_button("styles", "notebook") %>
		<label for="user_styles_notebook">Notebook</label><br />
		<%= f.radio_button("styles", "pulp") %>
		<label for="user_styles_pulp">Pulp</label><br />
		<%= f.submit "Update style", class: 'button button-primary' %>
	<% end %> -->

app/views/users/show.html.erb
<div class="translucent">
	<h2><%= @user.name %></h2>

	<section>
		<h3>Your profile</h3>
		<p><strong>Full name:</strong> <%= @user.name %></p>
		<p><strong>Blog name:</strong> <%= @user.handle %></p>
		<p><strong>Email:</strong> <%= @user.email %></p>
		<p><%= link_to 'Edit', edit_user_registration_path, class: "action-link" %></p>
	</section>

	<section>
	<h3>Your content</h3>
		<ul>
			<li><%= link_to 'Posts', user_post_items_path(@user.handle), class: "content-link" %></li>
			<% if @user.medium_detail %>
			<li><%= link_to 'Posts from Medium', user_medium_items_path(@user.handle), class: "content-link" %></li>
			<% end %>
			<% if @user.flickr_detail %>
			<li><%= link_to 'Photos from Flickr', user_flickr_items_path(@user.handle), class: "content-link" %></li>
			<% end %>
		</ul>
	</section>

	<section>	
		<h3>Modules</h3>
		<table>
			<tr>
				<th>Flickr</th>
				<td><%= @user.flickr_detail ? @user.flickr_detail.username : "-" %></td>
				<td>
					<% if @user.flickr_detail %>
						<%= link_to 'Update', edit_user_flickr_detail_path(@user.handle, @user.flickr_detail), class: "action-link" %>
					<% else %>
						<%= link_to 'Activate', new_user_flickr_detail_path(@user.handle), class: "action-link action-link" %>
					<% end %>
				</td>
			</tr>
			<tr>
				<th>Medium</th>
				<td><%= @user.medium_detail ? @user.medium_detail.username : "-" %></td>
				<td>
					<% if @user.medium_detail %>
						<%= link_to 'Update', edit_user_medium_detail_path(@user.handle, @user.medium_detail), class: "action-link" %>
					<% else %>
						<%= link_to 'Activate', new_user_medium_detail_path(@user.handle), class: "action-link action-link" %>
					<% end %>
				</td>
			</tr>
		</table>
</div><!-- end .translucent -->
	<div id="loader">
	  <!-- <div></div> loader animation -->
	  <div class="loader-container">
			<div id="trapezoid-mini"></div>
		  <div id="triangle-down-mini"></div>
		  <div id="trapezoid"></div>
		  <div id="triangle-down"></div>
	  </div>
	  <p>Getting your awesome content...</p>
	</div>
<div class="translucent">
		<% if @user.medium_detail || @user.flickr_detail %>
			<%= button_to 'Get content from modules!', user_sync_data_path, method: :post, class: "sync-data button" %>
		<% end %>
</section>
	<section>
		<h3>Customise style</h3>
		<p><strong>Blog style:</strong> <%= @user.styles %> 
		<%= link_to 'Change', user_edit_path(@user.handle), class: "action-link", id: "choose-style" %></p>

		<div id="edit-user-form">
			<%= render 'edit' %>
		</div>
	</section>

	<p><%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: "button-link button-link-primary" %></p>
	<p><%= link_to "Back", :back, class: "action-link" %></p>
</div><!-- end .translucent -->