config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/profile/:handle' => 'users#show', as: 'user'
  get 'users/profile/:handle/style' => 'users#edit', as: 'user_edit'
  put 'users/profile/:handle' => 'users#update'
  post 'users/profile/:handle' => 'users#sync_data', as: 'user_sync_data'
  get ':handle' => 'blog_items#index', as: 'user_index'

  resources :users, only: [] do
  	resources :post_items
  	resources :flickr_items
  	resources :medium_items
  	resources :flickr_details, except: [:index, :show]
  	resources :medium_details, except: [:index, :show]
  end

  resources :post_items, :medium_items, :flickr_items, only: [] do
  	resources :comments, only: [:create]
  end
end

app/models/post_item.rb
class PostItem < ActiveRecord::Base
	has_one :blog_item, as: :item, dependent: :destroy
	validates :title, :body, presence: true

	def author # check delegate to
		# TODO: Fix SQL performance
		blog_item.author
	end
end

app/controllers/post_items_controller.rb
class PostItemsController < ApplicationController
	before_action :find_post, only: [:edit, :update, :show]
	# doesn't work because instead of id ther's the user handle in the url
	before_action :authenticate_user!, except: [:show, :index]

	def index
		if params[:tag].present? 
       @posts = Post.where(tag: params[:tag])
			@posts = current_user.post_items.order(created_at: :desc)
     else 
			@posts = current_user.post_items.order(created_at: :desc)
     end
	end

	def new
		@post = PostItem.new
	end

	def create
		post = PostItem.new(title: params[:title], body: params[:body])
		tags = clean_tags_array(params[:tags])
		if post.save
			blog_item = create_blog_item(current_user, post)
			blog_item.create_or_find_tags(tags)
			redirect_to user_post_item_path(current_user.handle, post.id)
		else
			flash[:alert] = "A title and a body are required." 
			render :new
		end
	end

	def edit
		@tags = @post.blog_item.tags_to_string
	end

	def update
		@post.update(title: params[:title], body: params[:body])
		tags = clean_tags_array(params[:tags])
		@post.blog_item.create_or_find_tags(tags)
		redirect_to user_post_item_path(current_user.handle, @post), notice: "Post updated successfully."
	end

	def show
		@blog_user = @blog_user = User.find_by_handle(params[:user_id])
	end

	def destroy
		post = PostItem.find(params[:id])
		PostItem.destroy(post)
		redirect_to user_post_items_path(params[:user_id]), notice: "Post deleted successfully." #post.blog_item = nil, ?
	end

	private

	def find_post
		@post = PostItem.find(params[:id])
	end

	# def post_item_params
	# 	params.require(:post_item).permit(:title, :body)
	# end

	def create_blog_item(user, post)
		BlogItem.create!(user_id: user.id, item_id: post.id, item_type: 'PostItem')
	end

	def clean_tags_array(tags)
		tags = tags.split(',')
		tags.map { |tag| tag.strip }
	end
end

app/views/post_items/_post_item.html.erb
<h2><%= link_to post_item.title, user_post_item_path(params[:handle], post_item) %></h2>

<p class="meta">posted <%= time_ago_in_words(post_item.created_at) %> ago</p>

<article>

<%= md truncate(post_item.body, length: 350, separator: ' ') %>
</article>

<p>	
	<% post_item.blog_item.tags.each do |tag| %>
		<span class="label"><%= link_to tag.name, "/#{post_item.author.handle}?tag=#{tag.name}" %></span>
	<% end %>
</p>

<% if current_user && current_user.id == post_item.blog_item.user_id %>
<p><%= link_to 'Edit', edit_user_post_item_path(current_user, post_item), class: "action-link" %></p>
<% end %>

app/views/post_items/edit.html.erb
<h2>Update post</h2>
<p>Remember you can use <a href="http://daringfireball.net/projects/markdown/" target="_blank">Markdown</a>.</p>

<%= form_tag user_post_item_path, method: :put do %>
  <%= label_tag :title %>
  <%= text_field_tag :title, @post.title %>
  <%= label_tag :body %>
  <%= text_area_tag :body, @post.body %>
  <%= label_tag :tags, "Tags (separated by comma)" %>
  <%= text_field_tag :tags, @tags %>
  <%= submit_tag "Update post", class: "button button-primary" %>
<% end %>

<%= link_to 'Delete', user_post_item_path, method: :delete, data: { confirm: "Are you sure?" }, class: "action-link" %>

app/views/post_items/index.html.erb
<h2>Posts</h2>
<% unless @posts.blank? %>
	<table>
	<% @posts.each do |post| %>
		<tr>
			<th><%= link_to post.title, user_post_item_path(params[:user_id], post), class: "content-link" %></th>
			<td><%= link_to 'Edit', edit_user_post_item_path(current_user, post), class: "action-link" %></td>
			<td><%= link_to 'Delete', user_post_item_path(current_user, post), method: :delete, data: { confirm: "Are you sure?" }, class: "action-link" %></td>
		</tr>
	<% end %>
		
	</table>
<% else %>
	<p>No posts yet, <%= link_to 'create one!', new_user_post_item_path(current_user.handle), class: "action-link" %></p>
<% end %>

app/views/post_items/new.html.erb
<h2>Create a new post</h2>
<p>You can use <a href="http://daringfireball.net/projects/markdown/" target="_blank">Markdown</a>. <%= link_to "Fill in, dude.", "javascript:;", class: "guest-post action-link" %></p>
<%= form_tag(user_post_items_path) do %>
  <%= label_tag(:title) %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:body) %>
  <%= text_area_tag(:body) %>
  <%= label_tag(:tags, "Tags (separated by comma)") %>
  <%= text_field_tag(:tags) %>
  <%= submit_tag("Create post", class: "button") %>
<% end %>

app/views/post_items/show.html.erb
<h1><%= link_to @blog_user.handle, user_index_path(@blog_user.handle) %></h1>
<h2><%= @post.title %></h2>

<p class="meta">posted <%= time_ago_in_words(@post.created_at) %> ago</p>

<article><%= md @post.body %></article>

<p>	
	<% @post.blog_item.tags.each do |tag| %>
		<span class="label"><%= link_to tag.name, "/#{@post.author.handle}?tag=#{tag.name}" %></span>
	<% end %>
</p>

<%= render partial: 'shared/tweet', :locals => {item: @post} %>

<% if current_user && current_user.id == @post.blog_item.user_id %>
	<p><%= link_to 'Edit', edit_user_post_item_path(current_user, @post), class: "action-link" %></p>
<% end %>

<%= link_to "Back", :back, class: "action-link" %>

<h3 class="comments">Comments</h3>

<%= render partial: 'shared/comment_form', :locals => {item: @post} %>
<%= render partial: 'shared/comment', collection: @post.blog_item.comments %>