config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/profile/:handle' => 'users#show', as: 'user'
  get 'users/profile/:handle/style' => 'users#edit', as: 'user_edit'
  put 'users/profile/:handle' => 'users#update'
  post 'users/profile/:handle' => 'users#sync_data', as: 'user_sync_data'
  get ':handle' => 'blog_items#index', as: 'user_index'

  resources :users, only: [] do
  	resources :post_items
  	resources :flickr_items
  	resources :medium_items
  	resources :flickr_details, except: [:index, :show]
  	resources :medium_details, except: [:index, :show]
  end

  resources :post_items, :medium_items, :flickr_items, only: [] do
  	resources :comments, only: [:create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<% if @blog_user %>
    <% if @blog_user.styles == "notebook" %>
			<link href='//fonts.googleapis.com/css?family=Roboto:300,700|Pacifico' rel='stylesheet' type='text/css'>
		<% elsif @blog_user.styles == "pulp" %>
			<link href='//fonts.googleapis.com/css?family=Sigmar+One|Libre+Baskerville:400,400italic,700' rel='stylesheet' type='text/css'>
		<% elsif @blog_user.styles == "default" %>
			<link href='//fonts.googleapis.com/css?family=Lora:400,400italic,700|Ubuntu' rel='stylesheet' type='text/css'>
		<% end %>
	<% else %>
		<link href='//fonts.googleapis.com/css?family=Lora:400,400italic,700|Ubuntu' rel='stylesheet' type='text/css'>
	<% end %>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Happyblogging</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <% if @blog_user %>
  	<% if @blog_user.styles == "notebook" %>
	  	<link rel="stylesheet" media="all" href="<%= asset_path 'notebook/main.css' %>">
		<% elsif @blog_user.styles == "pulp" %>
	  	<link rel="stylesheet" media="all" href="<%= asset_path 'pulp/main.css' %>">
		<% end %>
  <% end %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container flex-container">
	<div>
		<a href="<%= root_path %>">
			<img class="logo" src=<%= image_path("logo.png") %> alt="Happy blogging logo">
		</a>
		<ul class="user-nav align-top">
			<% if current_user %>
				<li><%= link_to 'My site', user_index_path(current_user.handle) %></li>
		</ul>
	</div>
	<nav>
	<div>
		<ul class="user-nav">
			<li><%= link_to 'New post', new_user_post_item_path(current_user.handle) %></li>
			<li><%= link_to current_user.name, user_path(current_user.handle) %></li>
			<% else %>
				<li><%= link_to 'Sign up', new_user_registration_path %></li>
				<li><%= link_to 'Sign in', user_session_path %></li>
			<% end %>
		</ul>
	</div>
	</nav>
</header>

<main class="container">
	<% flash.each do |k, v| %>
	  <p class="message <%=k%>"><%= v %></p>
	<% end %>

 <%= yield %>
</main>

</body>
</html>